bookproject/accounts/urls.py
from django.urls import path


from . import views

app_name = 'accounts'
urlpatterns = [
		path("signup", views.signup, name="signup"),
  		path('login/', views.CustomLoginView.as_view(), name='login'),
		path('logout/', views.logout_to_book_library, name='logout'),
]

bookproject/book_library/urls.py
from django.urls import path

from . import views

app_name = 'book_library'
urlpatterns = [path("", views.show_books_list, name="books_list"),
			   path("add_book", views.add_book, name="add_book"),
			   path("add_author", views.add_author, name="add_author"),
			   path("<str:book_title>", views.book_details, name="book_details")
]

bookproject/bookproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("book_library.urls")),
    # path('accounts/', include("django.contrib.auth.urls")),
    path('accounts/', include("accounts.urls"))
]

bookproject/accounts/models.py
from django.db import models

# Create your models here.

bookproject/book_library/models.py
from django.db import models
from django.utils import timezone

class Author(models.Model):
	name = models.CharField(max_length=100, primary_key=True)
	STYLE_CHOICES = (("drama", "drama"), ("fiction", "fiction"), ("casual", "casual"), ("polar", "polar"))
	style = models.CharField(max_length=20, choices=STYLE_CHOICES)

	def __str__(self):
		return self.name

# Create your models here.
class Book(models.Model):
	title = models.CharField(max_length=200, primary_key=True)
	publication_date = models.DateField()
	author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='books')

bookproject/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class CustomSignUpForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')
        labels = {
            'username': 'Nom d’utilisateur',
            'email': 'Adresse email',
            'password1': 'Mot de passe',
            'password2': 'Confirmez votre mot de passe',
        }

bookproject/book_library/forms.py
from django import forms
from .models import Book, Author


class BookForm(forms.ModelForm):
	class Meta:
		model = Book
		fields = '__all__'


class AuthorForm(forms.ModelForm):
	class Meta:
		model = Author
		fields = "__all__"

bookproject/accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomSignUpForm
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView
from django.contrib import messages



# Create your views here.
def signup(request):
	if request.method == "GET":
		signup_form = CustomSignUpForm()
		
	elif request.method == "POST":
		signup_form = CustomSignUpForm(request.POST)
		if signup_form.is_valid():
			user = signup_form.save()
			login(request, user)
			return redirect("book_library:books_list")

	return render(request, "accounts/signup.html", {"signup_form" : signup_form})


class CustomLoginView(LoginView):
  template_name = 'accounts/login.html'
  next_page = 'book_library:books_list'

  def form_invalid(self, form):
      messages.error(self.request, "Invalid username or password")
      return super().form_invalid(form)






def logout_to_book_library(request):
    logout(request)
    return redirect("book_library:books_list")

bookproject/book_library/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import BookForm, AuthorForm
from .models import Book
from django.contrib.auth.decorators import login_required


# Create your views here.
def show_books_list(request):
	books = Book.objects.all().order_by('publication_date')
	return render(request, "book_library/books_list.html", {"books": books})


@login_required
def add_book(request):
	if request.method == "GET":
		book_form = BookForm()
	elif request.method == "POST":
		book_form = BookForm(request.POST)
		if book_form.is_valid():
			book_form.save()
			return redirect("book_library:books_list")

	return render(request, "book_library/add_book.html", {"book_form" : book_form})

@login_required
def add_author(request):
	if request.method == "GET":
		author_form = AuthorForm()
	elif request.method == "POST":
		author_form = AuthorForm(request.POST)
		if author_form.is_valid():
			author_form.save()
			return redirect("book_library:books_list")

	return render(request,"book_library/add_author.html", {"author_form" : author_form})



def book_details(request, book_title):
	book = get_object_or_404(Book, title=book_title)
	return render(request,  "book_library/book_details.html", {"book": book})

bookproject/accounts/templates/accounts/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
	<nav class="navbar navbar-expand-lg bg-body-tertiary">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="#">Book Library</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarSupportedContent">
	      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
	        <li class="nav-item">
	          <a class="nav-link active" aria-current="page" href="{% url 'book_library:books_list' %}">Home</a>
	        </li>
	       	<li class="nav-item">
	          <a class="nav-link active" aria-current="page" href="{%url 'book_library:add_author' %}">Add Author</a>
	        </li>
	       	<li class="nav-item">
	          <a class="nav-link active" aria-current="page" href="{% url 'book_library:add_book' %}">Add Book</a>
	        </li>
	      </ul>
	     <ul class="navbar-nav ml-auto">
	      {% if user.is_authenticated %}
	        <!-- Si l'utilisateur est connecté -->
	        <li class="nav-item">
	          <span class="nav-link">Bonjour, {{ user.username }} !</span>
	        </li>
	        <form action="{% url 'book_library:books_list' %}" method="post">
    				{% csrf_token %}
		        <li class="nav-item">
    					<button type="submit" class="btn btn-link nav-link">Se déconnecter</button>
		        </li>
		      </form>
	      {% else %}
	        <!-- Si l'utilisateur n'est pas connecté -->
	        <li class="nav-item">
	          <a class="nav-link" href="{% url 'accounts:signup' %}">S'inscrire</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link" href="{% url 'accounts:login' %}">Se connecter</a>
	        </li>
	      {% endif %}
	    </ul>
	    </div>
	  </div>
	</nav>

    <div class="container mt-4">
	   	{% block content %}
		{% endblock %}
    </div>

  </body>
</html>

bookproject/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block content %}
<div class="container mt-4">
    <h2>Se connecter</h2>
    <hr>

    {# Affichage des messages d’erreur ou de succès (ex: invalid username/password) #}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <form method="post" action="">
        {% csrf_token %}
         <div class="mb-3">
             <label for="id_username" class="form-label">Nom d'utilisateur</label>
             {{ form.username }}
         </div>
         <div class="mb-3">
             <label for="id_password" class="form-label">Mot de passe</label>
             {{ form.password }}
         </div>


        <button class="btn btn-primary" type="submit">Se connecter</button>
    </form>
</div>
{% endblock %}

bookproject/accounts/templates/accounts/signup.html
{% extends "accounts/base.html" %}

{% block title %} signup {% endblock %}
{% block content %}
<h1>Signup</h1>
<form method="POST">
	{% csrf_token %}
	  {# Afficher les erreurs globales s’il y en a #}
	  {{ signup_form.non_field_errors }}

	  <div>
	    {{ signup_form.username.label_tag }}
	    {{ signup_form.username }}
	    {{ signup_form.username.errors }}
	  </div>

	  <div>
	    {{ signup_form.email.label_tag }}
	    {{ signup_form.email }}
	    {{ signup_form.email.errors }}
	  </div>
	  
	  <div>
	    {{ signup_form.password1.label_tag }}
	    {{ signup_form.password1 }}
	    {{ signup_form.password1.errors }}
	  </div>

	  <div>
	    {{ signup_form.password2.label_tag }}
	    {{ signup_form.password2 }}
	    {{ signup_form.password2.errors }}
	  </div>

	<button type="submit" class="btn btn-outline-primary">Signup</button>
</form>	
{% endblock %}

bookproject/book_library/templates/book_library/add_author.html
{% extends 'book_library/base.html' %}

{% block title %}Add Author{% endblock %}


{% block content %}

<h1>Add author :</h1>
<form method="POST">
	{% csrf_token %}
	{{ author_form.as_p }}
	<button type="submit" class="btn btn-outline-primary">Ajouter</button>
</form>

{% endblock %}

bookproject/book_library/templates/book_library/add_book.html
{% block content %}
<h1>Ajouter un livre :</h1>
<form method="POST">
	{% csrf_token %}
	{{ book_form.as_p }}
	<button type="submit">Ajouter</button>
</form>
{% endblock %}

bookproject/book_library/templates/book_library/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
	<nav class="navbar navbar-expand-lg bg-body-tertiary">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="#">Book Library</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarSupportedContent">
	      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
	        <li class="nav-item">
	          <a class="nav-link active" aria-current="page" href="{% url 'books_list' %}">Home</a>
	        </li>
	       	<li class="nav-item">
	          <a class="nav-link active" aria-current="page" href="{%url 'add_author' %}">Add Author</a>
	        </li>
	       	<li class="nav-item">
	          <a class="nav-link active" aria-current="page" href="{% url 'add_book' %}">Add Book</a>
	        </li>

	      </ul>
	    </div>
	  </div>
	</nav>

    <div class="container mt-4">
	   	{% block content %}
		{% endblock %}
    </div>

  </body>
</html>

bookproject/book_library/templates/book_library/book_details.html
{% extends 'book_library/base.html' %}
{% block title %}book.title{% endblock %}
{% block content %}
<h1>{{book.title}}</h1>
<p>Auteur : {{book.author}}</p>
<p>Date de publication : {{book.publication_date}}</p>
{% endblock %}

bookproject/book_library/templates/book_library/books_list.html
{% extends 'book_library/base.html' %}
{% block title %}Listes des livres disponibles{% endblock %}
{% block content %}
<h1> Coucou les bgs de la DIA3 </h1>
{% for book in books %}
	<li>
		<a href="{% url 'book_library:book_details' book.title %}">
		{{book.title}} - {{book.author}}
		</a>
	</li>
{% endfor %}
{% endblock %}